name: 'uv-venv'
description: 'Setup uv (from Astral), create and activate virtual environment on Unix or Windows'
branding:
  color: 'yellow'

runs:
  using: 'composite'
  steps:
    - name: Setup UV, create and activate a virtual environment (Windows)
      shell: pwsh
      if: ${{ runner.os == 'Windows' }}
      run: |
        irm https://astral.sh/uv/install.ps1 | iex
        uv venv .venv
        "VIRTUAL_ENV=.venv" | Out-File -FilePath $env:GITHUB_ENV -Append
        "$PWD/.venv/Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Setup UV, create and activate a virtual environment (Unix)
      shell: bash
      if: ${{ runner.os != 'Windows' }}
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv .venv
        echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
